config/routes.rb
Nissa::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  
  ActiveAdmin.routes(self)
  
  root 'home_page#index'

  resources :news, only: [:index, :show]
  resources :activity_categories, only: [:index, :show]
  resources :partners, only: [:index]

  get 'projects' => 'projects#index'
  get 'clients' => 'clients#index'
  
  get 'contacts' => 'pages#contacts'
  get 'about' => 'pages#about'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :activity_category

  mount_uploader :image, ImageUploader
end

app/models/activity_category.rb
class ActivityCategory < ActiveRecord::Base
  has_many :activities
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :client_category
end

app/models/client_category.rb
class ClientCategory < ActiveRecord::Base
  has_many :clients
end

app/models/new.rb
class New < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/activity_categories_controller.rb
class ActivityCategoriesController < ApplicationController
  def show
    @activity_categories = ActivityCategory.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_slides

  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.superadmin?
      flash[:alert] = "Unauthorized Access!"
      redirect_to root_path
    end
  end

  def get_slides
    @slides = Slide.all
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @client_categories = ClientCategory.all
  end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
    @activity_categories = ActivityCategory.all
    @news = New.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = New.paginate(:page => params[:page], :per_page => 12)
  end

  def show
    @single_news = New.find(params[:id])
    @news = New.paginate(:page => params[:page], :per_page => 4)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contacts
  end

  def about
  end
  
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
    @partners = Partner.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    
    projects = Project.all

    projects_by_year = projects.group_by { |p| p.c_year }
    
    projects_by_year = projects_by_year.sort_by {|_key, value| -_key}

    @projects_by_year_by_month = Hash.new

    projects_by_year.each do |(key, projects)|
      @projects_by_year_by_month[key] = projects.group_by { |p| p.c_month }
    end

    @months = { 1 => "Январь",  2 => "Февраль",  3 => "Март",  4 => "Апрель",  5 => "Май",  6 => "Июнь",  7 => "Июль",  8 => "Август",  9 => "Сентябрь",  10 => "Октябрь",  11 => "Ноябрь",  12 => "Декабрь" }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active(path)
    path = path.split('/')[1] 
    request_path = request.path.split('/')[1] 
    if request_path
      return 'active' unless request_path["#{path}"].blank?
    end
  end
end

app/views/layouts/_slider.html.haml
%aside#slider
  #slider-glow
    #slider-content.wrapper
      %ul.slides
        - @slides.each do |slide|
          %li.slide= image_tag slide.image_url(:thumb_805)

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Официальный сайт компании "НИССА"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag 'http://api-maps.yandex.ru/2.1/?lang=ru_RU'
    = javascript_include_tag "application", "data-turbolinks-track" => true 
    = csrf_meta_tags
  %body
    #viewport
      %header
        .wrapper
          #header_in
            #logo
              = link_to root_path do
                = image_tag "logo.png", alt: "Нисса кондиционеры"
            #phone
              %p.title Контактный телефон:
              %p.phone +7 (4152) 41 03 45
          %nav#main-menu
            %ul.menu
              %li.item= link_to "О компании", about_path, class: active(about_path)
              %li.item= link_to "Новости", news_index_path, class: active(news_index_path)
              %li.item= link_to "Проекты", projects_path, class: active(projects_path)
              %li.item= link_to "Клиенты", clients_path, class: active(clients_path)
              %li.item= link_to "Партнеры", partners_path, class: active(partners_path)
              %li.item= link_to "Контакты", contacts_path, class: active(contacts_path)
      %main
        = render 'layouts/slider'
        = yield
    %footer
      .wrapper
        %p.copyright ООО "Нисса", 2014

app/views/pages/about.html.haml
#about
  .wrapper
    %h1 
      %i О нашей
      Компании
      %span
    %p 
      %strong 
        Общество с ограниченной ответственностью "НИССА"
      \- зарегистрировано 13 октября 2005 года в городе Петропавловске- Камчатском.
  #ceo-info
    .wrapper
      -# #profile
      -#   = image_tag "ceo-photo.jpg", alt: "Генеральный дректор Алексей Алексеевич Наголов"
        %p.work Генеральный директор 
        %p.name Алексей Алексеевич Наголов
      #speach
        Компания НИССА – является ведущей инженерной компанией Камчатского края осуществляющей работы по выполнению многопрофильных проектов в регионе. На сегодняшний день имеет офисные и складские помещения, а также собственный парк автомобилей, в т.ч. специального назначения. В июне 2014 г открыт розничный магазин климатического оборудования “Климат-Комфорт” по ул. Транспортный тупик 1. Цель нашей компании - предоставление полного спектра услуг по созданию комплексных информационных и инженерных систем различного уровня. Компания НИССА имеет многолетний опыт по интеграции систем различного уровня от самых простых типовых решений до уникальных комплексных проектов. Мы всегда придерживаемся принципа приоритета интересов заказчика. 
  .wrapper
    #services  
      %h1 
        %i Основные виды
        деятельности
        %span
      %ul.services
        %h2.header Приоритетными направлениями деятельности компании является поставка, монтаж и обслуживание:
        %li
          Инженерных систем – вентиляция, кондиционирование, отопление;
        %li
          Систем безопасности – пожарно-охранная сигнализация, охранная сигнализация, видеонаблюдение;
        %li
          Энергообеспечение – электромонтаж, замеры электролаборатории. Гарантированное бесперебойное электроснабжение – ИБП, ДГУ.
        %li
          Традиционная системная интеграция в сфере ИТ-технологий -продажа и внедрение информационных систем. Проектирование информационных систем. Структурированные кабельные системы. Телекоммуникации. Системы связи. Мультимедия.
        %li
          Строительство объектов.
      -# .columns
      -#   %ul.services
      -#     %h2.header Поставка оборудования
      -#     %li персональных компьютеров, серверов и ноутбуков;
      -#     %li поставка и установка офисного оборудования и оргтехники;
      -#     %li поставка и установка полиграфического оборудования;
      -#     %li поставка и установка лицензионного программного обеспечения;
      -#     %li активного и пассивного сетевого оборудования.
      -#   %ul.services
      -#     %h2.header Сервисное обслуживание
      -#     %li противопожарная обработка;
      -#     %li поставка и монтаж системы пожарно-охранной сигнализации;
      -#     %li услуги электролаборатории по испытаниям и измерениям электроустановок;
      -#     %li поставка и монтаж систем кондиционирования воздуха;
      -#     %li электромонтажные работы;
      -#     %li монтаж ЛВС и СКС;
      -#     %li монтаж систем видеонаблюдения;
      -#     %li поставка и монтаж систем контроля допуска;
      -#     %li поставка, монтаж и пуско-наладка дизель-генераторных установок.
      -# .columns
      -#   %ul.services
      -#     %h2.header Услуги
      -#     %li противопожарная обработка;
      -#     %li поставка и монтаж системы пожарно-охранной сигнализации;
      -#     %li услуги электролаборатории по испытаниям и измерениям электроустановок;
      -#     %li поставка и монтаж систем кондиционирования воздуха;
      -#     %li электромонтажные работы;
      -#     %li монтаж ЛВС и СКС;
      -#     %li монтаж систем видеонаблюдения;
      -#     %li поставка и монтаж систем контроля допуска;
      -#     %li поставка, монтаж и пуско-наладка дизель-генераторных установок.
    #documents
      %h1 
        %i Наши
        лицензии, свидетельства и сертификаты
        %span
      %ul.documents
        -# %li.work-certs
        -#   .image
        -#     = image_tag "documents/work-certs.jpg", alt: "Свидетельство о допуске к работам, которые оказывают влияние на безопасностьобъектов капитального строительства"
        -#   %p
        -#     %strong
        -#       Свидетельство о допуске к работам
        -#     ,которые оказывают влияние на безопасностьобъектов капитального строительства
        -#     %span №84-2009-4101103472-С-013
        
        -# %li.svidetelstvo
        -#   .image
        -#     = image_tag "documents/svidetelstvo.jpg", alt: "Свидетельство некоммерческого партнерства \"Союз Строителей Камчатки\" Серия СК №000227"
        -#   %p
        -#     %strong
        -#       Свидетельство некоммерческого партнерства "Союз Строителей Камчатки"
        -#     %span Серия СК №000227
        
        -# %li.license
        -#   .image
        -#     = image_tag "documents/license.jpg", alt: "Лицензия на производство работ по монтажу, ремонту и обслуживанию средств обеспечения пожарной безопасности зданий и сооружений №2/26374"
        -#   %p
        -#     %strong
        -#       Лицензия на производство работ по монтажу, ремонту и обслуживанию
        -#     средств обеспечения пожарной безопасности зданий и сооружений
        -#     %span №2/26374
        
        -# %li.svidetelstvo-2
        -#   .image
        -#     = image_tag "documents/svidetelstvo-2.jpg", alt: "Свидетельство о регистрации электролаборатории №Э-75-0047 от 27.02.2009"
        -#   %p
        -#     %strong
        -#       Свидетельство о регистрации электролаборатории
        -#     %span №Э-75-0047 от 27.02.2009

        -# %li.certs
        -#   .image
        -#     = image_tag "documents/cert-kentatsu.jpg", alt: "Сертификаты авторизованного дилера Kentatsu, Haier, Daikin"
        -#     = image_tag "documents/cert-haier-1.jpg", alt: "Сертификаты авторизованного дилера Kentatsu, Haier, Daikin"
        -#     = image_tag "documents/cert-daikin.jpg", alt: "Сертификаты авторизованного дилера Kentatsu, Haier, Daikin"
        -#   %p
        -#     %strong
        -#       Сертификаты авторизованного дилера 
        -#     %span Kentatsu, 
        -#     %span Haier, 
        -#     %span Daikin

        %li.certs.one
          .image
            = link_to "images/documents/sro2014_1.jpg", class: 'fancybox', data: { no_turbolink: true }, rel: 'lic1' do
              = image_tag "documents/prev_sro2014_1.jpg", alt: "Свидетельство о допуске работ"
            = link_to "images/documents/sro2014_2.jpg", class: 'fancybox', data: { no_turbolink: true }, rel: 'lic1' do
              = image_tag "documents/prev_sro2014_2.jpg", alt: "Свидетельство о допуске работ"
            = link_to "images/documents/sro2014_3.jpg", class: 'fancybox', data: { no_turbolink: true }, rel: 'lic1' do
              = image_tag "documents/prev_sro2014_3.jpg", alt: "Свидетельство о допуске работ"
          %p
            Свидетельство о допуске работ

        %li.certs.two
          .image
            = link_to "images/documents/electro_lic.jpg", class: 'fancybox', data: { no_turbolink: true } do
              = image_tag "documents/prev_electro_lic.jpg", alt: "Свидетельство о регистрации электро лаборатории"
          %p
            Свидетельство о регистрации электро лаборатории

        %li.certs.three
          .image
            = link_to "images/documents/mchs2013_1.jpg", class: 'fancybox', data: { no_turbolink: true }, rel: 'lic3' do
              = image_tag "documents/prev_mchs2013_1.jpg", alt: "Лицензия деятельности по монтажу, техническому обслуживанию и ремонту средств обеспечения пожарной безопасности зданий и сооружений"
            = link_to "images/documents/mchs2013_2.jpg", class: 'fancybox', data: { no_turbolink: true }, rel: 'lic3' do
              = image_tag "documents/prev_mchs2013_2.jpg", alt: "Лицензия деятельности по монтажу, техническому обслуживанию и ремонту средств обеспечения пожарной безопасности зданий и сооружений"
          %p
            Лицензия деятельности по монтажу, техническому обслуживанию и ремонту средств обеспечения пожарной безопасности зданий и сооружений

app/views/pages/contacts.html.haml
#contacts
  .wrapper
    %h1
      %i Наши
      контакты
      %span
  #map
  .wrapper
    #contact-data
      %ul
        %li
          %h2
            %i.placemark
            Адрес
          %p г.Петропавловск-Камчатский, 
          %p ул.Транспортный тупик д.1.
        %li
          %h2
            %i.phone
            Телефон/факс:
          %p +7 (4152) 41-03-45
        %li
          %h2
            %i.mail
            E-mail:
          %p nissa@nissa.kamchatka.ru

app/views/pages/partners.html.haml
#partners
  .wrapper
    %h1
      %i Наши
      Партнеры
      %span
  .white
    .wrapper
      = image_tag "partners/logo-1.jpg", alt: "company1"
      .company-info
        %h2
          %span Компания 
          "АБН"
        %p= link_to 'http://www.abn.ru'
        %ul
          %li 
            \- активное сетевое оборудование (сетевые адаптеры, концентраторы, коммутаторы, маршрутизаторы, трансиверы, конвертеры, серверы печати, источники бесперебойного питания);
          %li
            \- элементы кабельной системы (кабель, кабельные каналы, разъемы, розетки, патч-панели, патч-корды, шкафы и стойки, инструмент);
          %li
            \- поставка и монтаж фальшпола;
          %li
            \- проектирование и монтаж информационных (компьютерные сети и телефония) и силовых кабельных систем, включая волоконно-оптический монтаж.
        %p 
          Адрес: 
          %strong Москва, ул. Архитектора Власова, д. 49 
        %p
          Тел.: 
          %strong  (495) 995-10-10 (32 линии), 960-23-23 (8 линий), 755-88-13 (8 линий) 
        %p
          Факс: 
          %strong (495) 960-23-13 
        %p
          Е-mail: 
          %strong inf@abn.ru
  .blue
    .wrapper
      = image_tag "partners/logo-1.jpg", alt: "company1"
      .company-info
        %h2
          %span Компания 
          "АБН"
        %p= link_to 'http://www.abn.ru'
        %ul
          %li 
            \- активное сетевое оборудование (сетевые адаптеры, концентраторы, коммутаторы, маршрутизаторы, трансиверы, конвертеры, серверы печати, источники бесперебойного питания);
          %li
            \- элементы кабельной системы (кабель, кабельные каналы, разъемы, розетки, патч-панели, патч-корды, шкафы и стойки, инструмент);
          %li
            \- поставка и монтаж фальшпола;
          %li
            \- проектирование и монтаж информационных (компьютерные сети и телефония) и силовых кабельных систем, включая волоконно-оптический монтаж.
        %p 
          Адрес: 
          %strong Москва, ул. Архитектора Власова, д. 49 
        %p
          Тел.: 
          %strong  (495) 995-10-10 (32 линии), 960-23-23 (8 линий), 755-88-13 (8 линий) 
        %p
          Факс: 
          %strong (495) 960-23-13 
        %p
          Е-mail: 
          %strong inf@abn.ru
  .white
    .wrapper
      = image_tag "partners/logo-1.jpg", alt: "company1"
      .company-info
        %h2
          %span Компания 
          "АБН"
        %p= link_to 'http://www.abn.ru'
        %ul
          %li 
            \- активное сетевое оборудование (сетевые адаптеры, концентраторы, коммутаторы, маршрутизаторы, трансиверы, конвертеры, серверы печати, источники бесперебойного питания);
          %li
            \- элементы кабельной системы (кабель, кабельные каналы, разъемы, розетки, патч-панели, патч-корды, шкафы и стойки, инструмент);
          %li
            \- поставка и монтаж фальшпола;
          %li
            \- проектирование и монтаж информационных (компьютерные сети и телефония) и силовых кабельных систем, включая волоконно-оптический монтаж.
        %p 
          Адрес: 
          %strong Москва, ул. Архитектора Власова, д. 49 
        %p
          Тел.: 
          %strong  (495) 995-10-10 (32 линии), 960-23-23 (8 линий), 755-88-13 (8 линий) 
        %p
          Факс: 
          %strong (495) 960-23-13 
        %p
          Е-mail: 
          %strong inf@abn.ru